### PR TITLE
Remove as identifier

### PR DESCRIPTION
**Pull request by markGilchrist**

### CODE REVIEW

**Comment by dnharjani-sa** [comment]
Probably just want to work in a separate PR instead of adding / removing files

**Comment by dnharjani-sa** [comment]
Fat fingered the close button :(

**Comment by dnharjani-sa** [comment]
Looks good, probably worth removing this mock as well just to be 100% sure

https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/blob/master/Pod/Plugin/Core/Tests/Mocks/ASIdentifierManagerMock.swift

**Review by dnharjani-sa — APPROVED** [review]

**Comment by markGilchrist** [comment]
> Looks good, probably worth removing this mock as well just to be 100% sure
> 
> https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/blob/master/Pod/Plugin/Core/Tests/Mocks/ASIdentifierManagerMock.swift

8c84318de0c00d8303cf43096dffeba972dd9e43

**Review by dnharjani-sa — APPROVED** [review]

**Pull request merged**
